import stat
from pathlib import Path

from mcnet.domain.java import Runtime

SHELL_NAME = "start.sh"

BATCH_NAME = "start.bat"

NOTICE = "Generated by mcnet. Edit mcnet.yaml and run 'mcnet build' instead."

# Configs stay tracked on purpose: bukkit.yml, spigot.yml, config/ and the
# plugins' own settings are what a repo is for. Only what a run regenerates,
# or what belongs to one machine, is left out.
IGNORED = (
    "# mcnet: everything below is fetched or regenerated",
    "*.jar",
    "eula.txt",
    "world*/",
    "logs/",
    "cache/",
    "libraries/",
    "versions/",
    "usercache.json",
    "version_history.json",
    "plugins/.paper-remapped/",
    "lang/",
    "forwarding.secret",
)

GITIGNORE_NAME = ".gitignore"

GITATTRIBUTES_NAME = ".gitattributes"

# Without this, a repo written on Windows hands Linux a start.sh with CRLF
# line endings, and '#!/usr/bin/env sh\r' is not a program anyone has.
ATTRIBUTES = (
    "# mcnet: the shell launcher has to stay LF wherever it is checked out",
    f"{SHELL_NAME} text eol=lf",
    f"{BATCH_NAME} text eol=crlf",
)


def write(folder: Path, runtime: Runtime, jar: str, *, nogui: bool) -> list[Path]:
    """Write both launchers, so a repo cloned on the other OS still runs.

    Each one moves to its own folder first: people double click these from
    wherever, and a server started from the wrong directory writes its world
    somewhere surprising.
    """
    command = " ".join(runtime.command(jar, nogui=nogui))

    shell = folder / SHELL_NAME
    shell.write_text(
        f'#!/usr/bin/env sh\n# {NOTICE}\ncd "$(dirname "$0")"\nexec {command}\n',
        encoding="utf-8",
        newline="\n",
    )
    _make_runnable(shell)

    batch = folder / BATCH_NAME
    batch.write_text(
        f'@echo off\nREM {NOTICE}\ncd /d "%~dp0"\n{command}\npause\n',
        encoding="utf-8",
        newline="\r\n",
    )

    return [shell, batch]


def ignore(folder: Path) -> list[Path]:
    """Tell git what to skip and how to check the launchers out."""
    return [
        _append_missing(folder / GITIGNORE_NAME, IGNORED),
        _append_missing(folder / GITATTRIBUTES_NAME, ATTRIBUTES),
    ]


def _append_missing(path: Path, rules: tuple[str, ...]) -> Path:
    """Add what is not there yet, leaving anything the user wrote alone."""
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    known = set(lines)

    missing = [rule for rule in rules if rule not in known]

    if missing:
        if lines and lines[-1].strip():
            lines.append("")

        lines.extend(missing)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return path


def _make_runnable(path: Path) -> None:
    mode = path.stat().st_mode

    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
